import { PrismaClient } from "@prisma/client";
import { hash } from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting seed...");

  // ============================================
  // INVESTMENT INSIGHTS
  // ============================================
  console.log("📊 Seeding investment insights...");

  const insights = [
    // Municipal Bonds
    {
      type: "MUNICIPAL_BOND" as const,
      title: "Harris County Infrastructure Bond",
      description:
        "Harris County approved a $1.2 billion bond for flood control improvements, road repairs, and park renovations. Projects will focus on areas most affected by recent flooding events, including Buffalo Bayou improvements and drainage channel expansions.",
      source: "Harris County Bond Office",
      sourceUrl: "https://www.harriscountytx.gov/bonds",
      latitude: 29.7604,
      longitude: -95.3698,
      city: "Houston",
      county: "Harris",
      state: "TX",
      zipCode: "77002",
      impactRadiusMiles: 25,
      estimatedValue: 1200000000,
      fundingAmount: 1200000000,
      expectedROI: 12.5,
      projectYear: 2022,
      parcelsAffected: 4250,
      avgValueChange: 18.4,
      lagPeriodYears: 2.3,
      correlation: 0.72,
      announcedAt: new Date("2024-08-15"),
      expectedStart: new Date("2025-03-01"),
      expectedEnd: new Date("2028-12-31"),
      status: "ACTIVE" as const,
      tags: ["infrastructure", "flood-control", "transportation"],
    },
    {
      type: "MUNICIPAL_BOND" as const,
      title: "Dallas Transportation Bond Package",
      description:
        "Dallas voters approved $900 million in bonds for street and transportation improvements. Includes major intersection redesigns, pedestrian infrastructure, and bridge repairs across the city.",
      source: "Dallas City Council",
      sourceUrl: "https://dallascityhall.com/bonds",
      latitude: 32.7767,
      longitude: -96.797,
      city: "Dallas",
      county: "Dallas",
      state: "TX",
      zipCode: "75201",
      impactRadiusMiles: 20,
      estimatedValue: 900000000,
      fundingAmount: 900000000,
      expectedROI: 10.2,
      projectYear: 2021,
      parcelsAffected: 3180,
      avgValueChange: 15.2,
      lagPeriodYears: 2.8,
      correlation: 0.65,
      announcedAt: new Date("2024-11-05"),
      expectedStart: new Date("2025-06-01"),
      expectedEnd: new Date("2029-06-30"),
      status: "ACTIVE" as const,
      tags: ["transportation", "infrastructure", "streets"],
    },
    {
      type: "MUNICIPAL_BOND" as const,
      title: "Travis County Parks Bond",
      description:
        "Travis County issued $185 million in bonds for park improvements, trail connections, and recreational facility upgrades. Includes new swimming pools, sports fields, and nature preserve expansions.",
      source: "Travis County Parks Department",
      sourceUrl: "https://parks.traviscountytx.gov/bond",
      latitude: 30.2672,
      longitude: -97.7431,
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78701",
      impactRadiusMiles: 15,
      estimatedValue: 185000000,
      fundingAmount: 185000000,
      expectedROI: 8.5,
      projectYear: 2020,
      parcelsAffected: 1890,
      avgValueChange: 12.1,
      lagPeriodYears: 1.8,
      correlation: 0.58,
      announcedAt: new Date("2024-09-20"),
      expectedStart: new Date("2025-04-15"),
      expectedEnd: new Date("2027-09-30"),
      status: "ACTIVE" as const,
      tags: ["parks", "recreation", "quality-of-life"],
    },

    // School Construction
    {
      type: "SCHOOL_CONSTRUCTION" as const,
      title: "Frisco ISD New Elementary School",
      description:
        "Frisco ISD breaking ground on a new 850-student elementary school in the Panther Creek development. The $45 million facility will include state-of-the-art STEM labs, outdoor learning spaces, and a community gymnasium.",
      source: "Frisco ISD Board",
      sourceUrl: "https://www.friscoisd.org/construction",
      latitude: 33.1507,
      longitude: -96.8236,
      city: "Frisco",
      county: "Collin",
      state: "TX",
      zipCode: "75034",
      impactRadiusMiles: 5,
      estimatedValue: 45000000,
      fundingAmount: 45000000,
      expectedROI: 15.3,
      projectYear: 2021,
      parcelsAffected: 1247,
      avgValueChange: 22.3,
      lagPeriodYears: 1.5,
      correlation: 0.82,
      announcedAt: new Date("2024-06-01"),
      expectedStart: new Date("2025-01-15"),
      expectedEnd: new Date("2026-08-01"),
      status: "ACTIVE" as const,
      tags: ["education", "residential-growth", "family-friendly"],
    },
    {
      type: "SCHOOL_CONSTRUCTION" as const,
      title: "Katy ISD High School Expansion",
      description:
        "Katy ISD expanding Tompkins High School with a $78 million addition including new science wing, performing arts center, and athletics facilities. Expansion will increase capacity by 1,200 students.",
      source: "Katy ISD",
      sourceUrl: "https://www.katyisd.org/facilities",
      latitude: 29.7858,
      longitude: -95.8245,
      city: "Katy",
      county: "Harris",
      state: "TX",
      zipCode: "77494",
      impactRadiusMiles: 7,
      estimatedValue: 78000000,
      fundingAmount: 78000000,
      expectedROI: 14.8,
      projectYear: 2020,
      parcelsAffected: 2340,
      avgValueChange: 19.7,
      lagPeriodYears: 2.1,
      correlation: 0.78,
      announcedAt: new Date("2024-07-15"),
      expectedStart: new Date("2025-02-01"),
      expectedEnd: new Date("2027-01-15"),
      status: "ACTIVE" as const,
      tags: ["education", "high-school", "athletics"],
    },
    {
      type: "SCHOOL_CONSTRUCTION" as const,
      title: "Round Rock ISD Middle School",
      description:
        "New $52 million middle school in the rapidly growing Paloma Lake area. Will serve 1,100 students and feature innovative flexible learning spaces, a maker space, and an outdoor amphitheater.",
      source: "Round Rock ISD",
      sourceUrl: "https://roundrockisd.org/bond",
      latitude: 30.5083,
      longitude: -97.6789,
      city: "Round Rock",
      county: "Williamson",
      state: "TX",
      zipCode: "78665",
      impactRadiusMiles: 4,
      estimatedValue: 52000000,
      fundingAmount: 52000000,
      expectedROI: 16.1,
      projectYear: 2022,
      parcelsAffected: 890,
      avgValueChange: 24.1,
      lagPeriodYears: 1.2,
      correlation: 0.85,
      announcedAt: new Date("2024-10-01"),
      expectedStart: new Date("2025-05-01"),
      expectedEnd: new Date("2027-07-31"),
      status: "PENDING" as const,
      tags: ["education", "middle-school", "growth-area"],
    },

    // Road Projects
    {
      type: "ROAD_PROJECT" as const,
      title: "I-35 Expansion - Austin Central",
      description:
        "TxDOT approved $4.9 billion I-35 expansion through central Austin. Project will add managed lanes, lower the main lanes below grade through downtown, and create new pedestrian crossings connecting east and west Austin.",
      source: "Texas Department of Transportation",
      sourceUrl: "https://my35.org/",
      latitude: 30.2672,
      longitude: -97.7431,
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78701",
      impactRadiusMiles: 30,
      estimatedValue: 4900000000,
      fundingAmount: 4900000000,
      expectedROI: 11.2,
      projectYear: 2019,
      parcelsAffected: 8920,
      avgValueChange: 26.8,
      lagPeriodYears: 3.2,
      correlation: 0.88,
      announcedAt: new Date("2024-03-15"),
      expectedStart: new Date("2025-09-01"),
      expectedEnd: new Date("2033-12-31"),
      status: "ACTIVE" as const,
      tags: ["transportation", "highway", "major-infrastructure"],
    },
    {
      type: "ROAD_PROJECT" as const,
      title: "Loop 360 Improvements",
      description:
        "Major improvements to Loop 360 in Austin including new grade-separated intersections, widening, and safety improvements. Project aims to reduce congestion on this critical corridor.",
      source: "TxDOT Austin District",
      sourceUrl: "https://www.txdot.gov/projects/loop360",
      latitude: 30.3555,
      longitude: -97.8055,
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78746",
      impactRadiusMiles: 10,
      estimatedValue: 550000000,
      fundingAmount: 550000000,
      expectedROI: 9.8,
      projectYear: 2021,
      parcelsAffected: 2150,
      avgValueChange: 21.4,
      lagPeriodYears: 2.0,
      correlation: 0.79,
      announcedAt: new Date("2024-05-20"),
      expectedStart: new Date("2025-07-01"),
      expectedEnd: new Date("2028-06-30"),
      status: "ACTIVE" as const,
      tags: ["transportation", "highway", "traffic-relief"],
    },
    {
      type: "ROAD_PROJECT" as const,
      title: "SH 121 Extension - Collin County",
      description:
        "Extension of SH 121 through northeastern Collin County connecting to US 75. New tollway will improve access to growing communities in Celina and Prosper.",
      source: "NTTA",
      sourceUrl: "https://www.ntta.org/sh121",
      latitude: 33.2501,
      longitude: -96.7836,
      city: "Celina",
      county: "Collin",
      state: "TX",
      zipCode: "75009",
      impactRadiusMiles: 12,
      estimatedValue: 380000000,
      fundingAmount: 380000000,
      expectedROI: 13.5,
      projectYear: 2020,
      parcelsAffected: 3420,
      avgValueChange: 28.9,
      lagPeriodYears: 2.5,
      correlation: 0.91,
      announcedAt: new Date("2024-08-01"),
      expectedStart: new Date("2025-10-01"),
      expectedEnd: new Date("2028-03-31"),
      status: "PENDING" as const,
      tags: ["transportation", "tollway", "suburban-growth"],
    },
    // Grand Parkway (SH 99) Segment I-2 - Harris County
    {
      type: "ROAD_PROJECT" as const,
      title: "Grand Parkway Segment I-2",
      description:
        "Completion of Grand Parkway Segment I-2 connecting US 59 North to I-69. This final segment completes the 180-mile loop around Houston, improving regional connectivity and reducing commute times.",
      source: "TxDOT Houston District",
      sourceUrl: "https://www.grandpky.com",
      latitude: 30.0455,
      longitude: -95.2381,
      city: "Baytown",
      county: "Harris",
      state: "TX",
      zipCode: "77521",
      impactRadiusMiles: 15,
      estimatedValue: 1200000000,
      fundingAmount: 1200000000,
      expectedROI: 14.2,
      projectYear: 2022,
      parcelsAffected: 5680,
      avgValueChange: 31.2,
      lagPeriodYears: 1.8,
      correlation: 0.89,
      announcedAt: new Date("2023-06-01"),
      expectedStart: new Date("2024-01-15"),
      expectedEnd: new Date("2027-12-31"),
      status: "ACTIVE" as const,
      tags: ["transportation", "tollway", "regional-connectivity"],
    },

    // Development Permits
    {
      type: "DEVELOPMENT_PERMIT" as const,
      title: "The Domain North Expansion",
      description:
        "Major mixed-use development approved north of The Domain in Austin. 2.5 million sq ft of office, retail, and residential space. Expected to bring 5,000+ jobs and 2,000 residential units.",
      source: "Austin Planning Commission",
      sourceUrl: "https://austin.gov/planning/domain-north",
      latitude: 30.4021,
      longitude: -97.7239,
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78758",
      impactRadiusMiles: 3,
      estimatedValue: 850000000,
      fundingAmount: null,
      expectedROI: 18.5,
      projectYear: 2021,
      parcelsAffected: 1560,
      avgValueChange: 34.2,
      lagPeriodYears: 1.5,
      correlation: 0.86,
      announcedAt: new Date("2024-09-10"),
      expectedStart: new Date("2025-04-01"),
      expectedEnd: new Date("2029-12-31"),
      status: "ACTIVE" as const,
      tags: ["mixed-use", "office", "residential", "retail"],
    },
    {
      type: "DEVELOPMENT_PERMIT" as const,
      title: "Legacy West Phase 3",
      description:
        "Third phase of Legacy West development in Plano approved. Includes luxury apartment towers, boutique hotel, and additional retail/restaurant space adjacent to existing development.",
      source: "Plano Planning & Zoning",
      sourceUrl: "https://www.plano.gov/planning",
      latitude: 33.0762,
      longitude: -96.8286,
      city: "Plano",
      county: "Collin",
      state: "TX",
      zipCode: "75024",
      impactRadiusMiles: 2,
      estimatedValue: 420000000,
      fundingAmount: null,
      expectedROI: 16.2,
      projectYear: 2020,
      parcelsAffected: 890,
      avgValueChange: 29.5,
      lagPeriodYears: 1.8,
      correlation: 0.83,
      announcedAt: new Date("2024-11-01"),
      expectedStart: new Date("2025-06-15"),
      expectedEnd: new Date("2028-06-30"),
      status: "ACTIVE" as const,
      tags: ["mixed-use", "luxury", "hospitality", "residential"],
    },

    // Zoning Changes
    {
      type: "ZONING_CHANGE" as const,
      title: "East Riverside Corridor Rezoning",
      description:
        "Austin City Council approved comprehensive rezoning of East Riverside corridor from low-density commercial to high-density mixed-use. Expected to enable 15,000+ new housing units near Oracle campus.",
      source: "Austin City Council",
      sourceUrl: "https://austin.gov/zoning/east-riverside",
      latitude: 30.2294,
      longitude: -97.7155,
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78741",
      impactRadiusMiles: 3,
      estimatedValue: null,
      fundingAmount: null,
      expectedROI: 22.0,
      projectYear: 2019,
      parcelsAffected: 2340,
      avgValueChange: 42.5,
      lagPeriodYears: 2.2,
      correlation: 0.76,
      announcedAt: new Date("2024-10-15"),
      expectedStart: new Date("2025-01-01"),
      expectedEnd: null,
      status: "ACTIVE" as const,
      tags: ["zoning", "residential", "density", "transit-oriented"],
    },
    {
      type: "ZONING_CHANGE" as const,
      title: "Downtown Fort Worth Mixed-Use District",
      description:
        "Fort Worth approved creation of new mixed-use zoning district in downtown allowing taller buildings and reduced parking requirements. Encourages urban infill development.",
      source: "Fort Worth Planning",
      sourceUrl: "https://www.fortworthtexas.gov/planning",
      latitude: 32.7555,
      longitude: -97.3308,
      city: "Fort Worth",
      county: "Tarrant",
      state: "TX",
      zipCode: "76102",
      impactRadiusMiles: 1.5,
      estimatedValue: null,
      fundingAmount: null,
      expectedROI: 19.5,
      projectYear: 2020,
      parcelsAffected: 560,
      avgValueChange: 35.8,
      lagPeriodYears: 1.9,
      correlation: 0.71,
      announcedAt: new Date("2024-07-20"),
      expectedStart: new Date("2024-09-01"),
      expectedEnd: null,
      status: "ACTIVE" as const,
      tags: ["zoning", "urban-infill", "mixed-use", "downtown"],
    },

    // Infrastructure
    {
      type: "INFRASTRUCTURE" as const,
      title: "San Antonio Water System Expansion",
      description:
        "SAWS approved $2.1 billion infrastructure upgrade including new water treatment plant, pipeline expansions, and aquifer storage and recovery facilities to support growth through 2050.",
      source: "San Antonio Water System",
      sourceUrl: "https://www.saws.org/infrastructure",
      latitude: 29.4241,
      longitude: -98.4936,
      city: "San Antonio",
      county: "Bexar",
      state: "TX",
      zipCode: "78205",
      impactRadiusMiles: 35,
      estimatedValue: 2100000000,
      fundingAmount: 2100000000,
      expectedROI: 9.2,
      projectYear: 2021,
      parcelsAffected: 12500,
      avgValueChange: 13.2,
      lagPeriodYears: 3.5,
      correlation: 0.62,
      announcedAt: new Date("2024-04-01"),
      expectedStart: new Date("2025-01-15"),
      expectedEnd: new Date("2032-12-31"),
      status: "ACTIVE" as const,
      tags: ["water", "utilities", "long-term-growth"],
    },
    {
      type: "INFRASTRUCTURE" as const,
      title: "Houston Metro Purple Line",
      description:
        "METRO Houston proposing new Purple Line light rail connecting uptown to medical center and downtown. $3.8 billion project would add 18 stations and improve transit access for major employment centers.",
      source: "Houston METRO",
      sourceUrl: "https://www.ridemetro.org/purpleline",
      latitude: 29.7499,
      longitude: -95.3881,
      city: "Houston",
      county: "Harris",
      state: "TX",
      zipCode: "77027",
      impactRadiusMiles: 8,
      estimatedValue: 3800000000,
      fundingAmount: 3800000000,
      expectedROI: 14.5,
      projectYear: 2023,
      parcelsAffected: 6780,
      avgValueChange: 28.4,
      lagPeriodYears: 2.8,
      correlation: 0.81,
      announcedAt: new Date("2024-06-15"),
      expectedStart: new Date("2026-01-01"),
      expectedEnd: new Date("2032-06-30"),
      status: "PENDING" as const,
      tags: ["transit", "light-rail", "urban-development"],
    },
    // MUD District Water Infrastructure - Harris County
    {
      type: "INFRASTRUCTURE" as const,
      title: "Cypress Creek MUD Water Expansion",
      description:
        "Major water and wastewater infrastructure expansion for Cypress Creek Municipal Utility District. New treatment capacity will support 15,000 additional homes in the rapidly growing northwest Harris County area.",
      source: "Harris County MUD",
      sourceUrl: "https://www.hcmud.org/cypress-creek",
      latitude: 29.9618,
      longitude: -95.6531,
      city: "Cypress",
      county: "Harris",
      state: "TX",
      zipCode: "77433",
      impactRadiusMiles: 6,
      estimatedValue: 85000000,
      fundingAmount: 85000000,
      expectedROI: 11.8,
      projectYear: 2022,
      parcelsAffected: 3450,
      avgValueChange: 16.7,
      lagPeriodYears: 1.4,
      correlation: 0.69,
      announcedAt: new Date("2023-09-01"),
      expectedStart: new Date("2024-03-15"),
      expectedEnd: new Date("2026-08-31"),
      status: "ACTIVE" as const,
      tags: ["water", "wastewater", "suburban-growth", "MUD"],
    },

    // Tax Incentives
    {
      type: "TAX_INCENTIVE" as const,
      title: "Tesla Gigafactory Tax Abatement Extension",
      description:
        "Travis County extended property tax abatement for Tesla Gigafactory through 2035. Incentive tied to job creation targets and capital investment commitments totaling $10 billion.",
      source: "Travis County Commissioners Court",
      sourceUrl: "https://www.traviscountytx.gov/tesla",
      latitude: 30.2236,
      longitude: -97.6159,
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78725",
      impactRadiusMiles: 10,
      estimatedValue: 10000000000,
      fundingAmount: 150000000,
      expectedROI: 25.0,
      projectYear: 2021,
      parcelsAffected: 4560,
      avgValueChange: 52.3,
      lagPeriodYears: 1.5,
      correlation: 0.94,
      announcedAt: new Date("2024-08-20"),
      expectedStart: new Date("2024-09-01"),
      expectedEnd: new Date("2035-12-31"),
      status: "ACTIVE" as const,
      tags: ["manufacturing", "jobs", "automotive", "tech"],
    },
    {
      type: "TAX_INCENTIVE" as const,
      title: "Sherman Opportunity Zone - Texas Instruments",
      description:
        "City of Sherman approved major tax incentive package for Texas Instruments new $30 billion semiconductor fab. Expected to create 3,000+ direct jobs and thousands of construction jobs.",
      source: "Sherman Economic Development",
      sourceUrl: "https://www.shermantx.gov/edc/ti",
      latitude: 33.6357,
      longitude: -96.6089,
      city: "Sherman",
      county: "Grayson",
      state: "TX",
      zipCode: "75090",
      impactRadiusMiles: 20,
      estimatedValue: 30000000000,
      fundingAmount: 750000000,
      expectedROI: 28.5,
      projectYear: 2022,
      parcelsAffected: 8900,
      avgValueChange: 67.8,
      lagPeriodYears: 2.0,
      correlation: 0.92,
      announcedAt: new Date("2024-02-15"),
      expectedStart: new Date("2024-05-01"),
      expectedEnd: new Date("2030-12-31"),
      status: "ACTIVE" as const,
      tags: ["semiconductor", "manufacturing", "jobs", "tech"],
    },
    // Additional Harris County projects for better data density
    {
      type: "SCHOOL_CONSTRUCTION" as const,
      title: "Cypress-Fairbanks ISD Elementary",
      description:
        "New elementary school in the Bridgeland master-planned community. $42 million facility will serve 950 students with innovative learning spaces and community amenities.",
      source: "Cy-Fair ISD",
      sourceUrl: "https://www.cfisd.net/facilities",
      latitude: 29.9521,
      longitude: -95.6843,
      city: "Cypress",
      county: "Harris",
      state: "TX",
      zipCode: "77433",
      impactRadiusMiles: 4,
      estimatedValue: 42000000,
      fundingAmount: 42000000,
      expectedROI: 17.2,
      projectYear: 2023,
      parcelsAffected: 1120,
      avgValueChange: 21.5,
      lagPeriodYears: 1.3,
      correlation: 0.84,
      announcedAt: new Date("2024-01-15"),
      expectedStart: new Date("2024-06-01"),
      expectedEnd: new Date("2026-08-15"),
      status: "ACTIVE" as const,
      tags: ["education", "elementary", "master-planned"],
    },
    {
      type: "ROAD_PROJECT" as const,
      title: "Highway 290 Widening - NW Harris",
      description:
        "TxDOT widening US 290 from 6 to 10 lanes through northwest Harris County. Project includes new frontage roads, improved drainage, and enhanced pedestrian facilities.",
      source: "TxDOT Houston",
      sourceUrl: "https://www.txdot.gov/us290-harris",
      latitude: 29.8901,
      longitude: -95.5921,
      city: "Houston",
      county: "Harris",
      state: "TX",
      zipCode: "77040",
      impactRadiusMiles: 8,
      estimatedValue: 720000000,
      fundingAmount: 720000000,
      expectedROI: 12.8,
      projectYear: 2021,
      parcelsAffected: 4230,
      avgValueChange: 23.6,
      lagPeriodYears: 2.4,
      correlation: 0.83,
      announcedAt: new Date("2022-11-01"),
      expectedStart: new Date("2023-04-15"),
      expectedEnd: new Date("2027-12-31"),
      status: "ACTIVE" as const,
      tags: ["transportation", "highway", "widening"],
    },
    {
      type: "INFRASTRUCTURE" as const,
      title: "Clear Lake City Water Authority Upgrade",
      description:
        "Major upgrade to Clear Lake area water treatment and distribution system. Project will increase capacity by 40% and improve water quality for southeast Harris County residents.",
      source: "CLCWA",
      sourceUrl: "https://www.clcwa.org/upgrade",
      latitude: 29.5516,
      longitude: -95.1185,
      city: "Clear Lake",
      county: "Harris",
      state: "TX",
      zipCode: "77062",
      impactRadiusMiles: 7,
      estimatedValue: 156000000,
      fundingAmount: 156000000,
      expectedROI: 10.5,
      projectYear: 2022,
      parcelsAffected: 5670,
      avgValueChange: 14.8,
      lagPeriodYears: 2.1,
      correlation: 0.67,
      announcedAt: new Date("2023-03-20"),
      expectedStart: new Date("2024-01-10"),
      expectedEnd: new Date("2027-06-30"),
      status: "ACTIVE" as const,
      tags: ["water", "utilities", "upgrade"],
    },
  ];

  for (const insight of insights) {
    await prisma.investmentInsight.upsert({
      where: {
        id: insight.title
          .toLowerCase()
          .replace(/[^a-z0-9]/g, "-")
          .slice(0, 20),
      },
      update: {},
      create: {
        id: insight.title
          .toLowerCase()
          .replace(/[^a-z0-9]/g, "-")
          .slice(0, 20),
        ...insight,
        estimatedValue: insight.estimatedValue ?? undefined,
        fundingAmount: insight.fundingAmount ?? undefined,
        expectedEnd: insight.expectedEnd ?? undefined,
      },
    });
  }
  console.log(`✅ Created ${insights.length} investment insights`);

  // ============================================
  // PROPERTY OWNERS
  // ============================================
  console.log("🏠 Seeding property owners...");

  const propertyOwners = [
    // Harris County properties
    {
      parcelId: "HC-2024-001234",
      county: "Harris",
      addressLine1: "1234 Westheimer Rd",
      city: "Houston",
      state: "TX",
      zipCode: "77006",
      ownerName: "Westheimer Properties LLC",
      ownerType: "corporation",
      mailingAddress: "PO Box 12345, Houston, TX 77001",
      phone: "(713) 555-0101",
      email: "info@westheimerprop.com",
      latitude: 29.7423,
      longitude: -95.4019,
      lotSizeSqft: 45000,
      zoning: "MU-3",
      landUse: "Commercial",
      assessedValue: 2850000,
      taxAmount: 68400,
      lastSaleDate: new Date("2019-03-15"),
      lastSalePrice: 2100000,
      dataSource: "harris_county_cad",
    },
    {
      parcelId: "HC-2024-005678",
      county: "Harris",
      addressLine1: "5678 Memorial Dr",
      city: "Houston",
      state: "TX",
      zipCode: "77024",
      ownerName: "Memorial Land Trust",
      ownerType: "trust",
      mailingAddress: "1000 Main St Suite 500, Houston, TX 77002",
      phone: "(713) 555-0202",
      email: "trust@memorialland.com",
      latitude: 29.7752,
      longitude: -95.4568,
      lotSizeSqft: 125000,
      zoning: "SF-1",
      landUse: "Vacant Land",
      assessedValue: 8500000,
      taxAmount: 204000,
      lastSaleDate: new Date("2015-08-20"),
      lastSalePrice: 5200000,
      dataSource: "harris_county_cad",
    },
    {
      parcelId: "HC-2024-009012",
      county: "Harris",
      addressLine1: "9012 Katy Fwy",
      city: "Houston",
      state: "TX",
      zipCode: "77079",
      ownerName: "Energy Corridor Investments Inc",
      ownerType: "corporation",
      mailingAddress: "9012 Katy Fwy, Houston, TX 77079",
      phone: "(281) 555-0303",
      email: "leasing@energycorridorinv.com",
      latitude: 29.7878,
      longitude: -95.6065,
      lotSizeSqft: 350000,
      zoning: "C-2",
      landUse: "Commercial",
      assessedValue: 15600000,
      taxAmount: 374400,
      lastSaleDate: new Date("2021-11-30"),
      lastSalePrice: 14200000,
      dataSource: "harris_county_cad",
    },

    // Travis County properties
    {
      parcelId: "TC-2024-001111",
      county: "Travis",
      addressLine1: "1111 South Congress Ave",
      city: "Austin",
      state: "TX",
      zipCode: "78704",
      ownerName: "SoCo Development Partners",
      ownerType: "partnership",
      mailingAddress: "500 W 5th St, Austin, TX 78701",
      phone: "(512) 555-0111",
      email: "dev@socopartners.com",
      latitude: 30.2469,
      longitude: -97.7501,
      lotSizeSqft: 32000,
      zoning: "CS-MU-V-CO",
      landUse: "Mixed Use",
      assessedValue: 6200000,
      taxAmount: 136400,
      lastSaleDate: new Date("2018-06-01"),
      lastSalePrice: 3800000,
      dataSource: "tcad_public_records",
    },
    {
      parcelId: "TC-2024-002222",
      county: "Travis",
      addressLine1: "2222 E Riverside Dr",
      city: "Austin",
      state: "TX",
      zipCode: "78741",
      ownerName: "Riverside Holdings LLC",
      ownerType: "corporation",
      mailingAddress: "2222 E Riverside Dr, Austin, TX 78741",
      phone: "(512) 555-0222",
      email: "info@riversideholdings.com",
      latitude: 30.2294,
      longitude: -97.7255,
      lotSizeSqft: 180000,
      zoning: "MF-6",
      landUse: "Multifamily",
      assessedValue: 28500000,
      taxAmount: 627000,
      lastSaleDate: new Date("2020-09-15"),
      lastSalePrice: 22000000,
      dataSource: "tcad_public_records",
    },
    {
      parcelId: "TC-2024-003333",
      county: "Travis",
      addressLine1: "3333 N Lamar Blvd",
      city: "Austin",
      state: "TX",
      zipCode: "78705",
      ownerName: "John and Mary Smith",
      ownerType: "individual",
      mailingAddress: "3333 N Lamar Blvd, Austin, TX 78705",
      phone: "(512) 555-0333",
      email: null,
      latitude: 30.3015,
      longitude: -97.7475,
      lotSizeSqft: 18500,
      zoning: "GO-MU",
      landUse: "Office",
      assessedValue: 1850000,
      taxAmount: 40700,
      lastSaleDate: new Date("2005-04-10"),
      lastSalePrice: 650000,
      dataSource: "tcad_public_records",
    },

    // Collin County properties
    {
      parcelId: "CC-2024-004444",
      county: "Collin",
      addressLine1: "4444 Legacy Dr",
      city: "Plano",
      state: "TX",
      zipCode: "75024",
      ownerName: "Legacy Business Park LP",
      ownerType: "partnership",
      mailingAddress: "4444 Legacy Dr Suite 100, Plano, TX 75024",
      phone: "(972) 555-0444",
      email: "leasing@legacybp.com",
      latitude: 33.0762,
      longitude: -96.8086,
      lotSizeSqft: 520000,
      zoning: "PD-O",
      landUse: "Office",
      assessedValue: 42000000,
      taxAmount: 882000,
      lastSaleDate: new Date("2022-01-20"),
      lastSalePrice: 38500000,
      dataSource: "collin_cad",
    },
    {
      parcelId: "CC-2024-005555",
      county: "Collin",
      addressLine1: "5555 Preston Rd",
      city: "Frisco",
      state: "TX",
      zipCode: "75034",
      ownerName: "Preston Development Group",
      ownerType: "corporation",
      mailingAddress: "5555 Preston Rd, Frisco, TX 75034",
      phone: "(469) 555-0555",
      email: "dev@prestongroup.com",
      latitude: 33.1507,
      longitude: -96.8016,
      lotSizeSqft: 95000,
      zoning: "C-1",
      landUse: "Vacant Land",
      assessedValue: 4750000,
      taxAmount: 99750,
      lastSaleDate: new Date("2023-05-01"),
      lastSalePrice: 4200000,
      dataSource: "collin_cad",
    },

    // Bexar County properties
    {
      parcelId: "BC-2024-006666",
      county: "Bexar",
      addressLine1: "6666 Broadway",
      city: "San Antonio",
      state: "TX",
      zipCode: "78209",
      ownerName: "Broadway Retail Partners",
      ownerType: "partnership",
      mailingAddress: "200 E Houston St, San Antonio, TX 78205",
      phone: "(210) 555-0666",
      email: "retail@broadwaysa.com",
      latitude: 29.4832,
      longitude: -98.4623,
      lotSizeSqft: 68000,
      zoning: "C-3",
      landUse: "Commercial",
      assessedValue: 5400000,
      taxAmount: 118800,
      lastSaleDate: new Date("2017-12-01"),
      lastSalePrice: 3900000,
      dataSource: "bcad_records",
    },
    {
      parcelId: "BC-2024-007777",
      county: "Bexar",
      addressLine1: "7777 UTSA Blvd",
      city: "San Antonio",
      state: "TX",
      zipCode: "78249",
      ownerName: "UTSA Boulevard Investments LLC",
      ownerType: "corporation",
      mailingAddress: "7777 UTSA Blvd Suite 200, San Antonio, TX 78249",
      phone: "(210) 555-0777",
      email: "invest@utsablvd.com",
      latitude: 29.5855,
      longitude: -98.6201,
      lotSizeSqft: 215000,
      zoning: "MU-1",
      landUse: "Mixed Use",
      assessedValue: 18200000,
      taxAmount: 400400,
      lastSaleDate: new Date("2021-07-15"),
      lastSalePrice: 15500000,
      dataSource: "bcad_records",
    },

    // Dallas County properties
    {
      parcelId: "DC-2024-008888",
      county: "Dallas",
      addressLine1: "8888 Main St",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      ownerName: "Downtown Dallas Properties Inc",
      ownerType: "corporation",
      mailingAddress: "8888 Main St, Dallas, TX 75201",
      phone: "(214) 555-0888",
      email: "info@downtowndallas.com",
      latitude: 32.7827,
      longitude: -96.7968,
      lotSizeSqft: 42000,
      zoning: "CA-1(A)",
      landUse: "Commercial",
      assessedValue: 32000000,
      taxAmount: 736000,
      lastSaleDate: new Date("2019-10-01"),
      lastSalePrice: 28000000,
      dataSource: "dcad_records",
    },
    {
      parcelId: "DC-2024-009999",
      county: "Dallas",
      addressLine1: "9999 Cedar Springs Rd",
      city: "Dallas",
      state: "TX",
      zipCode: "75219",
      ownerName: "Oak Lawn Land Company",
      ownerType: "corporation",
      mailingAddress: "9999 Cedar Springs Rd, Dallas, TX 75219",
      phone: "(214) 555-0999",
      email: "leasing@oaklawnland.com",
      latitude: 32.8096,
      longitude: -96.8065,
      lotSizeSqft: 28000,
      zoning: "MU-3",
      landUse: "Mixed Use",
      assessedValue: 8500000,
      taxAmount: 195500,
      lastSaleDate: new Date("2020-03-15"),
      lastSalePrice: 7200000,
      dataSource: "dcad_records",
    },

    // Williamson County properties
    {
      parcelId: "WC-2024-010101",
      county: "Williamson",
      addressLine1: "10101 N IH 35",
      city: "Round Rock",
      state: "TX",
      zipCode: "78681",
      ownerName: "Round Rock Commerce Center LLC",
      ownerType: "corporation",
      mailingAddress: "10101 N IH 35, Round Rock, TX 78681",
      phone: "(512) 555-1010",
      email: "info@rrcommerce.com",
      latitude: 30.5283,
      longitude: -97.6789,
      lotSizeSqft: 420000,
      zoning: "C-3",
      landUse: "Industrial",
      assessedValue: 24500000,
      taxAmount: 514500,
      lastSaleDate: new Date("2022-08-01"),
      lastSalePrice: 21000000,
      dataSource: "wcad_records",
    },
    {
      parcelId: "WC-2024-011111",
      county: "Williamson",
      addressLine1: "11111 Sam Bass Rd",
      city: "Round Rock",
      state: "TX",
      zipCode: "78665",
      ownerName: "Elizabeth Johnson Family Trust",
      ownerType: "trust",
      mailingAddress: "PO Box 1111, Round Rock, TX 78680",
      phone: "(512) 555-1111",
      email: "ejohnson.trust@email.com",
      latitude: 30.5483,
      longitude: -97.6389,
      lotSizeSqft: 85000,
      zoning: "SF-6",
      landUse: "Vacant Land",
      assessedValue: 2125000,
      taxAmount: 44625,
      lastSaleDate: new Date("2008-02-01"),
      lastSalePrice: 425000,
      dataSource: "wcad_records",
    },
  ];

  for (const owner of propertyOwners) {
    await prisma.propertyOwner.upsert({
      where: {
        parcelId_county: {
          parcelId: owner.parcelId,
          county: owner.county,
        },
      },
      update: {},
      create: owner,
    });
  }
  console.log(`✅ Created ${propertyOwners.length} property owners`);

  // ============================================
  // ENGINEER DIRECTORY
  // ============================================
  console.log("🔧 Seeding engineer directory...");

  const engineers = [
    // Houston Area Engineers
    {
      companyName: "Texas Geotechnical Engineering Inc",
      contactName: "Dr. Robert Martinez",
      phone: "(713) 555-2001",
      email: "rmartinez@texasgeotech.com",
      website: "https://www.texasgeotech.com",
      addressLine1: "4500 Post Oak Blvd Suite 300",
      city: "Houston",
      county: "Harris",
      state: "TX",
      zipCode: "77027",
      latitude: 29.7499,
      longitude: -95.4605,
      serviceRadiusMiles: 75,
      specialties: ["soil", "geotechnical", "environmental"],
      licenseNumber: "PE-87234",
      licenseState: "TX",
      certifications: ["PG", "ENV-SP"],
      rating: 4.8,
      reviewCount: 127,
      isVerified: true,
      isActive: true,
    },
    {
      companyName: "Gulf Coast Drainage Solutions",
      contactName: "Sarah Thompson, PE",
      phone: "(281) 555-2002",
      email: "sthompson@gulfcoastdrainage.com",
      website: "https://www.gulfcoastdrainage.com",
      addressLine1: "12000 Katy Fwy Suite 450",
      city: "Houston",
      county: "Harris",
      state: "TX",
      zipCode: "77079",
      latitude: 29.7878,
      longitude: -95.6065,
      serviceRadiusMiles: 60,
      specialties: ["drainage", "civil", "stormwater"],
      licenseNumber: "PE-92156",
      licenseState: "TX",
      certifications: ["CFM", "CPESC"],
      rating: 4.7,
      reviewCount: 89,
      isVerified: true,
      isActive: true,
    },
    {
      companyName: "Structural Integrity Engineers",
      contactName: "Michael Chen, PE, SE",
      phone: "(713) 555-2003",
      email: "mchen@structuralintegrity.com",
      website: "https://www.structuralintegrity.com",
      addressLine1: "1800 Bering Dr Suite 600",
      city: "Houston",
      county: "Harris",
      state: "TX",
      zipCode: "77057",
      latitude: 29.7521,
      longitude: -95.4652,
      serviceRadiusMiles: 100,
      specialties: ["structural", "civil"],
      licenseNumber: "PE-78543",
      licenseState: "TX",
      certifications: ["SE"],
      rating: 4.9,
      reviewCount: 156,
      isVerified: true,
      isActive: true,
    },

    // Austin Area Engineers
    {
      companyName: "Central Texas Soil Consultants",
      contactName: "James Wilson, PG",
      phone: "(512) 555-3001",
      email: "jwilson@centraltexassoil.com",
      website: "https://www.centraltexassoil.com",
      addressLine1: "8000 Research Blvd Suite 200",
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78758",
      latitude: 30.3755,
      longitude: -97.7239,
      serviceRadiusMiles: 80,
      specialties: ["soil", "geotechnical", "environmental"],
      licenseNumber: "PG-4521",
      licenseState: "TX",
      certifications: ["PG", "RG"],
      rating: 4.6,
      reviewCount: 94,
      isVerified: true,
      isActive: true,
    },
    {
      companyName: "Austin Civil Engineering Group",
      contactName: "Emily Rodriguez, PE",
      phone: "(512) 555-3002",
      email: "erodriguez@austincivil.com",
      website: "https://www.austincivil.com",
      addressLine1: "3500 Jefferson St Suite 400",
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78731",
      latitude: 30.3455,
      longitude: -97.7631,
      serviceRadiusMiles: 50,
      specialties: ["civil", "drainage", "survey"],
      licenseNumber: "PE-95678",
      licenseState: "TX",
      certifications: ["LEED AP", "CFM"],
      rating: 4.8,
      reviewCount: 112,
      isVerified: true,
      isActive: true,
    },
    {
      companyName: "Hill Country Environmental Services",
      contactName: "David Anderson, PE",
      phone: "(512) 555-3003",
      email: "danderson@hillcountryenv.com",
      website: "https://www.hillcountryenv.com",
      addressLine1: "1601 S MoPac Expy Suite 300",
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78746",
      latitude: 30.2655,
      longitude: -97.8055,
      serviceRadiusMiles: 65,
      specialties: ["environmental", "soil", "water-quality"],
      licenseNumber: "PE-88901",
      licenseState: "TX",
      certifications: ["ENV-SP", "QSD"],
      rating: 4.5,
      reviewCount: 67,
      isVerified: true,
      isActive: true,
    },

    // Dallas-Fort Worth Area Engineers
    {
      companyName: "North Texas Geotechnical Services",
      contactName: "William Brown, PE, PG",
      phone: "(214) 555-4001",
      email: "wbrown@ntxgeotech.com",
      website: "https://www.ntxgeotech.com",
      addressLine1: "5001 LBJ Fwy Suite 800",
      city: "Dallas",
      county: "Dallas",
      state: "TX",
      zipCode: "75244",
      latitude: 32.9207,
      longitude: -96.8209,
      serviceRadiusMiles: 70,
      specialties: ["geotechnical", "soil", "structural"],
      licenseNumber: "PE-76234",
      licenseState: "TX",
      certifications: ["PG", "D.GE"],
      rating: 4.7,
      reviewCount: 143,
      isVerified: true,
      isActive: true,
    },
    {
      companyName: "Metroplex Civil Engineers",
      contactName: "Jennifer Lee, PE",
      phone: "(972) 555-4002",
      email: "jlee@metroplexcivil.com",
      website: "https://www.metroplexcivil.com",
      addressLine1: "2001 Bryan St Suite 2200",
      city: "Dallas",
      county: "Dallas",
      state: "TX",
      zipCode: "75201",
      latitude: 32.7887,
      longitude: -96.7968,
      serviceRadiusMiles: 55,
      specialties: ["civil", "drainage", "transportation"],
      licenseNumber: "PE-82567",
      licenseState: "TX",
      certifications: ["PTOE", "CFM"],
      rating: 4.6,
      reviewCount: 98,
      isVerified: true,
      isActive: true,
    },
    {
      companyName: "Fort Worth Structural Engineering",
      contactName: "Richard Taylor, PE, SE",
      phone: "(817) 555-4003",
      email: "rtaylor@fwstructural.com",
      website: "https://www.fwstructural.com",
      addressLine1: "777 Main St Suite 1200",
      city: "Fort Worth",
      county: "Tarrant",
      state: "TX",
      zipCode: "76102",
      latitude: 32.7555,
      longitude: -97.3308,
      serviceRadiusMiles: 60,
      specialties: ["structural", "civil"],
      licenseNumber: "PE-71890",
      licenseState: "TX",
      certifications: ["SE", "SECB"],
      rating: 4.9,
      reviewCount: 134,
      isVerified: true,
      isActive: true,
    },

    // San Antonio Area Engineers
    {
      companyName: "Alamo Geotechnical Engineers",
      contactName: "Carlos Garcia, PE",
      phone: "(210) 555-5001",
      email: "cgarcia@alamogeotech.com",
      website: "https://www.alamogeotech.com",
      addressLine1: "100 NE Loop 410 Suite 500",
      city: "San Antonio",
      county: "Bexar",
      state: "TX",
      zipCode: "78216",
      latitude: 29.5155,
      longitude: -98.4636,
      serviceRadiusMiles: 75,
      specialties: ["geotechnical", "soil", "environmental"],
      licenseNumber: "PE-84321",
      licenseState: "TX",
      certifications: ["PG", "GE"],
      rating: 4.6,
      reviewCount: 78,
      isVerified: true,
      isActive: true,
    },
    {
      companyName: "South Texas Drainage Specialists",
      contactName: "Maria Santos, PE",
      phone: "(210) 555-5002",
      email: "msantos@stxdrainage.com",
      website: "https://www.stxdrainage.com",
      addressLine1: "8400 Blanco Rd Suite 200",
      city: "San Antonio",
      county: "Bexar",
      state: "TX",
      zipCode: "78216",
      latitude: 29.5255,
      longitude: -98.5136,
      serviceRadiusMiles: 60,
      specialties: ["drainage", "civil", "stormwater"],
      licenseNumber: "PE-89654",
      licenseState: "TX",
      certifications: ["CFM", "CPSWQ"],
      rating: 4.7,
      reviewCount: 89,
      isVerified: true,
      isActive: true,
    },

    // Collin County Engineers
    {
      companyName: "Plano Engineering Associates",
      contactName: "Kevin Wright, PE",
      phone: "(972) 555-6001",
      email: "kwright@planoeng.com",
      website: "https://www.planoeng.com",
      addressLine1: "5000 Legacy Dr Suite 250",
      city: "Plano",
      county: "Collin",
      state: "TX",
      zipCode: "75024",
      latitude: 33.0762,
      longitude: -96.8086,
      serviceRadiusMiles: 45,
      specialties: ["civil", "structural", "drainage"],
      licenseNumber: "PE-91234",
      licenseState: "TX",
      certifications: ["LEED AP", "CFM"],
      rating: 4.8,
      reviewCount: 121,
      isVerified: true,
      isActive: true,
    },
    {
      companyName: "Frisco Soil & Foundation Consultants",
      contactName: "Amanda Clark, PG",
      phone: "(469) 555-6002",
      email: "aclark@friscosoil.com",
      website: "https://www.friscosoil.com",
      addressLine1: "6801 Gaylord Pkwy Suite 200",
      city: "Frisco",
      county: "Collin",
      state: "TX",
      zipCode: "75034",
      latitude: 33.1507,
      longitude: -96.8236,
      serviceRadiusMiles: 50,
      specialties: ["soil", "geotechnical"],
      licenseNumber: "PG-5678",
      licenseState: "TX",
      certifications: ["PG", "RG"],
      rating: 4.5,
      reviewCount: 56,
      isVerified: true,
      isActive: true,
    },

    // Williamson County Engineers
    {
      companyName: "Round Rock Civil & Survey",
      contactName: "Thomas Miller, PE, RPLS",
      phone: "(512) 555-7001",
      email: "tmiller@rrcivil.com",
      website: "https://www.rrcivil.com",
      addressLine1: "1601 S IH 35 Suite 400",
      city: "Round Rock",
      county: "Williamson",
      state: "TX",
      zipCode: "78664",
      latitude: 30.5083,
      longitude: -97.6789,
      serviceRadiusMiles: 55,
      specialties: ["civil", "survey", "drainage"],
      licenseNumber: "PE-86543",
      licenseState: "TX",
      certifications: ["RPLS", "CFM"],
      rating: 4.7,
      reviewCount: 92,
      isVerified: true,
      isActive: true,
    },
    {
      companyName: "Georgetown Environmental Engineering",
      contactName: "Patricia White, PE",
      phone: "(512) 555-7002",
      email: "pwhite@georgetownenv.com",
      website: "https://www.georgetownenv.com",
      addressLine1: "1530 Sun City Blvd Suite 100",
      city: "Georgetown",
      county: "Williamson",
      state: "TX",
      zipCode: "78633",
      latitude: 30.6583,
      longitude: -97.6789,
      serviceRadiusMiles: 45,
      specialties: ["environmental", "soil", "water-quality"],
      licenseNumber: "PE-93210",
      licenseState: "TX",
      certifications: ["ENV-SP", "QSD"],
      rating: 4.6,
      reviewCount: 64,
      isVerified: true,
      isActive: true,
    },
  ];

  for (const engineer of engineers) {
    // Generate a deterministic ID from company name
    const engineerId = engineer.companyName
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "-")
      .slice(0, 25);

    await prisma.engineerDirectory.upsert({
      where: { id: engineerId },
      update: {},
      create: {
        id: engineerId,
        ...engineer,
      },
    });
  }
  console.log(`✅ Created ${engineers.length} engineers`);

  // ============================================
  // TEST USERS
  // ============================================
  console.log("👤 Seeding test users...");

  const hashedPassword = await hash("Test123!", 12);

  // Create ADMIN user
  const adminUser = await prisma.user.upsert({
    where: { email: "admin@truplat.com" },
    update: {},
    create: {
      email: "admin@truplat.com",
      password: hashedPassword,
      firstName: "Admin",
      lastName: "User",
      role: "ADMIN",
      status: "ACTIVE",
    },
  });
  console.log(`  ✅ Admin user: admin@truplat.com / Test123!`);

  // Create CLIENT organization
  const testOrg = await prisma.organization.upsert({
    where: { slug: "test-investment-corp" },
    update: {},
    create: {
      name: "Test Investment Corp",
      slug: "test-investment-corp",
      billingEmail: "contact@testinvestment.com",
      phone: "(512) 555-0001",
      plan: "PROFESSIONAL",
      seats: 10,
    },
  });

  // Create CLIENT user with organization
  const clientUser = await prisma.user.upsert({
    where: { email: "client@truplat.com" },
    update: {},
    create: {
      email: "client@truplat.com",
      password: hashedPassword,
      firstName: "Client",
      lastName: "User",
      role: "CLIENT",
      status: "ACTIVE",
      organizationId: testOrg.id,
    },
  });
  console.log(`  ✅ Client user: client@truplat.com / Test123!`);

  // Create APPRAISER user with profile
  const appraiserUser = await prisma.user.upsert({
    where: { email: "appraiser@truplat.com" },
    update: {},
    create: {
      email: "appraiser@truplat.com",
      password: hashedPassword,
      firstName: "John",
      lastName: "Appraiser",
      phone: "(512) 555-0002",
      role: "APPRAISER",
      status: "ACTIVE",
    },
  });

  // Create appraiser profile
  await prisma.appraiserProfile.upsert({
    where: { userId: appraiserUser.id },
    update: {},
    create: {
      userId: appraiserUser.id,
      licenseNumber: "TX-12345",
      licenseState: "TX",
      licenseType: "CERTIFIED_RESIDENTIAL",
      licenseExpiry: new Date("2026-12-31"),
      homeBaseLat: 30.2672,
      homeBaseLng: -97.7431,
      coverageRadiusMiles: 50,
      verificationStatus: "VERIFIED",
      rating: 4.8,
      completedJobs: 150,
    },
  });
  console.log(`  ✅ Appraiser user: appraiser@truplat.com / Test123!`);

  // Create some test properties and jobs for the map
  console.log("🏠 Creating test properties and jobs...");

  const testProperties = [
    {
      id: "prop-001",
      parcelId: "TRAVIS-001234",
      addressLine1: "123 Congress Ave",
      addressFull: "123 Congress Ave, Austin, TX 78701",
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
      propertyType: "COMMERCIAL" as const,
    },
    {
      id: "prop-002",
      parcelId: "TRAVIS-005678",
      addressLine1: "456 South Lamar Blvd",
      addressFull: "456 South Lamar Blvd, Austin, TX 78704",
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78704",
      latitude: 30.2519,
      longitude: -97.7678,
      propertyType: "SINGLE_FAMILY" as const,
    },
    {
      id: "prop-003",
      parcelId: "HARRIS-001234",
      addressLine1: "789 Westheimer Rd",
      addressFull: "789 Westheimer Rd, Houston, TX 77006",
      city: "Houston",
      county: "Harris",
      state: "TX",
      zipCode: "77006",
      latitude: 29.7423,
      longitude: -95.3974,
      propertyType: "MULTI_FAMILY" as const,
    },
  ];

  for (const prop of testProperties) {
    await prisma.property.upsert({
      where: { id: prop.id },
      update: {},
      create: prop,
    });
  }

  // Create test jobs
  const schedulingWindow = JSON.stringify({
    start: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    end: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
  });

  const testJobs = [
    {
      id: "job-001",
      propertyId: "prop-001",
      organizationId: testOrg.id,
      jobType: "ONSITE_PHOTOS" as const,
      status: "PENDING_DISPATCH" as const,
      scope: "Exterior photos, front and back. Interior photos if accessible.",
      schedulingWindow,
      payoutAmount: 150,
      slaDueAt: new Date(Date.now() + 48 * 60 * 60 * 1000), // 48 hours from now
    },
    {
      id: "job-002",
      propertyId: "prop-002",
      organizationId: testOrg.id,
      assignedAppraiserId: appraiserUser.id,
      jobType: "CERTIFIED_APPRAISAL" as const,
      status: "ACCEPTED" as const,
      scope: "Full certified appraisal with interior/exterior inspection.",
      schedulingWindow,
      payoutAmount: 350,
      slaDueAt: new Date(Date.now() + 72 * 60 * 60 * 1000), // 72 hours from now
    },
    {
      id: "job-003",
      propertyId: "prop-003",
      organizationId: testOrg.id,
      assignedAppraiserId: appraiserUser.id,
      jobType: "ONSITE_PHOTOS" as const,
      status: "IN_PROGRESS" as const,
      scope: "Residential property assessment with land survey review.",
      schedulingWindow,
      payoutAmount: 175,
      slaDueAt: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours from now
    },
  ];

  for (const job of testJobs) {
    await prisma.job.upsert({
      where: { id: job.id },
      update: {},
      create: job,
    });
  }
  console.log(
    `  ✅ Created ${testProperties.length} properties and ${testJobs.length} jobs`,
  );

  // ============================================
  // DD MARKETPLACE LISTINGS
  // ============================================
  console.log("🛒 Seeding DD Marketplace listings...");

  const marketplaceListings = [
    // Phase I ESA Documents
    {
      id: "listing-esa-001",
      title: "Phase I Environmental Site Assessment - Commercial Property",
      description:
        "Comprehensive Phase I ESA conducted in June 2024 for 2.5-acre commercial site. Includes site reconnaissance, historical research, regulatory database review, and interviews. No RECs identified.",
      category: "commercial",
      studyCategory: "ENVIRONMENTAL" as const,
      price: 500,
      city: "Spring",
      county: "Montgomery",
      state: "TX",
      zipCode: "77386",
      latitude: 30.0799,
      longitude: -95.4172,
      viewCount: 42,
      soldCount: 3,
    },
    {
      id: "listing-esa-002",
      title: "Phase I ESA - Industrial Warehouse Complex",
      description:
        "Phase I Environmental Assessment for 15-acre industrial site in Pasadena. Historical use review, vapor intrusion screening, and regulatory compliance check included. Clean findings.",
      category: "industrial",
      studyCategory: "ENVIRONMENTAL" as const,
      price: 750,
      city: "Pasadena",
      county: "Harris",
      state: "TX",
      zipCode: "77506",
      latitude: 29.6911,
      longitude: -95.2091,
      viewCount: 28,
      soldCount: 1,
    },
    {
      id: "listing-esa-003",
      title: "Phase I ESA - Retail Shopping Center",
      description:
        "Environmental assessment for 8-acre retail development site. Former agricultural use. Includes wetland delineation and threatened species habitat review.",
      category: "commercial",
      studyCategory: "ENVIRONMENTAL" as const,
      price: 600,
      city: "Sugar Land",
      county: "Fort Bend",
      state: "TX",
      zipCode: "77479",
      latitude: 29.6197,
      longitude: -95.6349,
      viewCount: 35,
      soldCount: 2,
    },

    // Surveys
    {
      id: "listing-survey-001",
      title: "ALTA Survey - 5-Acre Development Site",
      description:
        "ALTA/NSPS Land Title Survey completed March 2024 for 5-acre mixed-use development site. Includes topographic information, easements, utilities, flood zone determination.",
      category: "land",
      studyCategory: "SURVEY" as const,
      price: 750,
      city: "Tomball",
      county: "Harris",
      state: "TX",
      zipCode: "77375",
      latitude: 30.0972,
      longitude: -95.6161,
      viewCount: 68,
      soldCount: 5,
    },
    {
      id: "listing-survey-002",
      title: "Boundary Survey - 12-Acre Ranch Property",
      description:
        "Complete boundary survey with corner monumentation for 12-acre rural property. Includes legal description, adjacent property information, and fence line analysis.",
      category: "land",
      studyCategory: "SURVEY" as const,
      price: 450,
      city: "Magnolia",
      county: "Montgomery",
      state: "TX",
      zipCode: "77354",
      latitude: 30.2091,
      longitude: -95.7508,
      viewCount: 24,
      soldCount: 1,
    },
    {
      id: "listing-survey-003",
      title: "Topographic Survey - Commercial Lot",
      description:
        "Detailed topographic survey for 3-acre commercial site. 1-foot contours, spot elevations, existing utilities, and drainage patterns mapped.",
      category: "commercial",
      studyCategory: "SURVEY" as const,
      price: 550,
      city: "Katy",
      county: "Harris",
      state: "TX",
      zipCode: "77494",
      latitude: 29.7858,
      longitude: -95.8245,
      viewCount: 31,
      soldCount: 2,
    },

    // Civil Engineering Plans
    {
      id: "listing-civil-001",
      title: "Civil Engineering Plans - Multi-Family Development",
      description:
        "Complete civil engineering plan set for 150-unit multi-family development. Includes site plan, grading, drainage, utility design, paving, erosion control, and construction details.",
      category: "residential",
      studyCategory: "CIVIL_ENGINEERING" as const,
      price: 1200,
      city: "The Woodlands",
      county: "Montgomery",
      state: "TX",
      zipCode: "77380",
      latitude: 30.1658,
      longitude: -95.4613,
      viewCount: 91,
      soldCount: 7,
    },
    {
      id: "listing-civil-002",
      title: "Site Development Plans - Retail Pad Site",
      description:
        "Civil plans for 2-acre retail pad site development. Includes site grading, parking lot design, stormwater management, and utility connections.",
      category: "commercial",
      studyCategory: "CIVIL_ENGINEERING" as const,
      price: 800,
      city: "Pearland",
      county: "Brazoria",
      state: "TX",
      zipCode: "77584",
      latitude: 29.5636,
      longitude: -95.286,
      viewCount: 45,
      soldCount: 3,
    },

    // Geotechnical Reports
    {
      id: "listing-geotech-001",
      title: "Geotechnical Investigation - High-Rise Foundation",
      description:
        "Comprehensive geotechnical study for 20-story mixed-use building. Includes 8 borings to 150ft, laboratory testing, foundation recommendations, and seismic analysis.",
      category: "commercial",
      studyCategory: "GEOTECHNICAL" as const,
      price: 2500,
      city: "Houston",
      county: "Harris",
      state: "TX",
      zipCode: "77002",
      latitude: 29.7604,
      longitude: -95.3698,
      viewCount: 156,
      soldCount: 4,
    },
    {
      id: "listing-geotech-002",
      title: "Geotechnical Report - Single Family Subdivision",
      description:
        "Geotechnical engineering report for 50-lot residential subdivision. Soil borings, plasticity index testing, and foundation design parameters for slab-on-grade construction.",
      category: "residential",
      studyCategory: "GEOTECHNICAL" as const,
      price: 950,
      city: "Cypress",
      county: "Harris",
      state: "TX",
      zipCode: "77433",
      latitude: 29.9691,
      longitude: -95.6972,
      viewCount: 38,
      soldCount: 2,
    },

    // Title Reports
    {
      id: "listing-title-001",
      title: "Title Commitment & Survey - Office Building",
      description:
        "Full title commitment with Schedule B exceptions, plus ALTA survey for 50,000 SF office building. Includes easement research and encumbrance analysis.",
      category: "commercial",
      studyCategory: "TITLE_REPORT" as const,
      price: 400,
      city: "Dallas",
      county: "Dallas",
      state: "TX",
      zipCode: "75201",
      latitude: 32.7767,
      longitude: -96.797,
      viewCount: 52,
      soldCount: 6,
    },
    {
      id: "listing-title-002",
      title: "Title Search - Vacant Land Parcel",
      description:
        "60-year title search for 25-acre vacant land parcel. Chain of title, lien search, judgment search, and tax status verification included.",
      category: "land",
      studyCategory: "TITLE_REPORT" as const,
      price: 300,
      city: "Austin",
      county: "Travis",
      state: "TX",
      zipCode: "78748",
      latitude: 30.1821,
      longitude: -97.8102,
      viewCount: 29,
      soldCount: 2,
    },

    // Zoning Analysis
    {
      id: "listing-zoning-001",
      title: "Zoning Analysis & Entitlement Report",
      description:
        "Comprehensive zoning analysis for proposed mixed-use development. Includes permitted uses, setbacks, height limits, parking requirements, and variance recommendations.",
      category: "commercial",
      studyCategory: "ZONING_ANALYSIS" as const,
      price: 650,
      city: "San Antonio",
      county: "Bexar",
      state: "TX",
      zipCode: "78205",
      latitude: 29.4241,
      longitude: -98.4936,
      viewCount: 41,
      soldCount: 3,
    },

    // Soil Studies
    {
      id: "listing-soil-001",
      title: "Soil Percolation Test - Septic System Design",
      description:
        "Percolation testing and soil analysis for residential septic system. Includes soil boring logs, absorption rate calculations, and system sizing recommendations.",
      category: "residential",
      studyCategory: "SOIL_STUDY" as const,
      price: 350,
      city: "Dripping Springs",
      county: "Hays",
      state: "TX",
      zipCode: "78620",
      latitude: 30.1902,
      longitude: -98.0867,
      viewCount: 18,
      soldCount: 1,
    },

    // Drainage Studies
    {
      id: "listing-drainage-001",
      title: "Drainage Impact Analysis - Subdivision Development",
      description:
        "Detailed drainage study for 100-acre residential subdivision. Includes pre/post hydrology, detention pond design, outfall analysis, and FEMA coordination.",
      category: "residential",
      studyCategory: "DRAINAGE_STUDY" as const,
      price: 1100,
      city: "League City",
      county: "Galveston",
      state: "TX",
      zipCode: "77573",
      latitude: 29.5075,
      longitude: -95.0949,
      viewCount: 63,
      soldCount: 4,
    },

    // Structural Reports
    {
      id: "listing-structural-001",
      title: "Structural Assessment - Historic Building Renovation",
      description:
        "Structural condition assessment for 1920s commercial building. Includes foundation evaluation, load capacity analysis, and renovation recommendations.",
      category: "commercial",
      studyCategory: "STRUCTURAL" as const,
      price: 850,
      city: "Fort Worth",
      county: "Tarrant",
      state: "TX",
      zipCode: "76102",
      latitude: 32.7555,
      longitude: -97.3308,
      viewCount: 37,
      soldCount: 2,
    },

    // Flood Risk
    {
      id: "listing-flood-001",
      title: "Flood Risk Assessment & LOMA Application",
      description:
        "Comprehensive flood risk analysis with FEMA Letter of Map Amendment application. Includes elevation certificate, hydraulic analysis, and flood insurance recommendations.",
      category: "residential",
      studyCategory: "FLOOD_RISK" as const,
      price: 550,
      city: "Humble",
      county: "Harris",
      state: "TX",
      zipCode: "77338",
      latitude: 29.9988,
      longitude: -95.2622,
      viewCount: 44,
      soldCount: 3,
    },
  ];

  for (const listing of marketplaceListings) {
    await prisma.marketplaceListing.upsert({
      where: { id: listing.id },
      update: {},
      create: {
        ...listing,
        sellerId: testOrg.id,
        status: "ACTIVE",
      },
    });
  }
  console.log(
    `  ✅ Created ${marketplaceListings.length} marketplace listings`,
  );

  console.log("");
  console.log("═══════════════════════════════════════════════════");
  console.log("  TEST ACCOUNTS CREATED:");
  console.log("═══════════════════════════════════════════════════");
  console.log("  🔑 Admin:     admin@truplat.com     / Test123!");
  console.log("  🔑 Client:    client@truplat.com    / Test123!");
  console.log("  🔑 Appraiser: appraiser@truplat.com / Test123!");
  console.log("═══════════════════════════════════════════════════");
  console.log("");

  console.log("🎉 Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
